In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
engine = create_engine(
    "postgresql://username:password@localhost:5432/ecommerce_db
)

In [4]:
df = pd.read_sql (
    """SELECT
    customer_unique_id,
    order_purchase_date
    FROM ecommerce_order_view""",
    engine
)
df.head()

                 customer_unique_id order_purchase_date
0  eb28e67c4c0b83846050ddfb8a35d051          2017-04-26
1  3818d81c6709e39d06b2738a8d3a2474          2018-01-14
2  107e6259485efac66428a56f10801f4f          2018-03-24
3  3fb97204945ca0c01bcf3eee6031c5f1          2018-07-27
4  7ed0ea20347f67fe61d1c99fdf8556ae          2018-07-24

In [5]:
df['order_purchase_date'].dtype

dtype('O')

In [6]:
df['order_purchase_date'] = pd.to_datetime(
    df['order_purchase_date']
)

In [7]:
df = df[
    (df['order_purchase_date'] >= '2017-01-01') &
    (df['order_purchase_date'] <= '2018-08-31')
]

In [8]:
# Creating cohort month
df['cohort_month'] = (
    df.groupby('customer_unique_id')
    ['order_purchase_date'].transform('min')
)
df.head()

                 customer_unique_id order_purchase_date cohort_month
0  eb28e67c4c0b83846050ddfb8a35d051          2017-04-26   2017-04-26
1  3818d81c6709e39d06b2738a8d3a2474          2018-01-14   2018-01-14
2  107e6259485efac66428a56f10801f4f          2018-03-24   2018-03-24
3  3fb97204945ca0c01bcf3eee6031c5f1          2018-07-27   2018-07-27
4  7ed0ea20347f67fe61d1c99fdf8556ae          2018-07-24   2018-07-24

In [9]:
df['cohort_month'] = (
    df['cohort_month'].dt.to_period('M')
)

df['order_month'] = (
    df['order_purchase_date'].dt.to_period('M')
)

df.head()

,customer_unique_id,order_purchase_date,cohort_month,order_month
0,eb28e67c4c0b83846050ddfb8a35d051,2017-04-26,2017-04,2017-04
1,3818d81c6709e39d06b2738a8d3a2474,2018-01-14,2018-01,2018-01
2,107e6259485efac66428a56f10801f4f,2018-03-24,2018-03,2018-03
3,3fb97204945ca0c01bcf3eee6031c5f1,2018-07-27,2018-07,2018-07
4,7ed0ea20347f67fe61d1c99fdf8556ae,2018-07-24,2018-07,2018-07

In [10]:
df['cohort_index'] = (
    (df['order_month'].dt.year - df['cohort_month'].dt.year) *12
    +
    (df['order_month'].dt.month - df['cohort_month'].dt.month)
)

df.head()

,customer_unique_id,order_purchase_date,cohort_month,order_month,cohort_index
0,eb28e67c4c0b83846050ddfb8a35d051,2017-04-26,2017-04,2017-04,0
1,3818d81c6709e39d06b2738a8d3a2474,2018-01-14,2018-01,2018-01,0
2,107e6259485efac66428a56f10801f4f,2018-03-24,2018-03,2018-03,0
3,3fb97204945ca0c01bcf3eee6031c5f1,2018-07-27,2018-07,2018-07,0
4,7ed0ea20347f67fe61d1c99fdf8556ae,2018-07-24,2018-07,2018-07,0

In [11]:
df[df['cohort_index'] > 0].head()

,customer_unique_id,order_purchase_date,cohort_month,order_month,cohort_index
36,6204c4e582a95b6a350adf6988623bfb,2017-10-18,2017-09,2017-10,1
67,297ec5afd18366f5ba27520cc4954151,2018-04-18,2018-02,2018-04,2
69,013ef03e0f3f408dd9bf555e4edcdc0a,2018-07-20,2018-06,2018-07,1
80,d567f29ec5fa447c99e949f337f3a35c,2017-12-15,2017-08,2017-12,4
118,c2919fbdb45366551c1e80d5cb35cd3f,2017-11-01,2017-09,2017-11,2

In [12]:
cohort_data = (
    df.groupby(['cohort_month', 'cohort_index'])
    ['customer_unique_id'].nunique().reset_index()
)

In [13]:
cohort_data.rename(
    columns={
        'customer_unique_id': 'total_customers'
    },
    inplace=True
)
cohort_data.head()

  cohort_month  cohort_index  total_customers
0      2017-01             0              765
1      2017-01             1                3
2      2017-01             2                2
3      2017-01             3                1
4      2017-01             4                3

In [14]:
cohort_matrix = cohort_data.pivot(
    index= 'cohort_month',
    columns ='cohort_index',
    values = 'total_customers'
)

cohort_matrix.head()

cohort_index,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19
cohort_month,,,,,,,,,,,,,,,,,,,
2017-01,765.0,3.0,2.0,1.0,3.0,1.0,4.0,1.0,1.0,NaN,3.0,1.0,6.0,3.0,1.0,1.0,2.0,3.0,1.0
2017-02,1752.0,4.0,5.0,2.0,7.0,2.0,4.0,3.0,3.0,4.0,2.0,5.0,3.0,3.0,2.0,1.0,1.0,4.0,NaN
2017-03,2636.0,13.0,10.0,10.0,9.0,4.0,4.0,8.0,9.0,2.0,10.0,4.0,6.0,3.0,4.0,6.0,2.0,4.0,NaN
2017-04,2353.0,14.0,5.0,4.0,8.0,6.0,8.0,7.0,7.0,4.0,6.0,2.0,2.0,1.0,2.0,2.0,5.0,NaN,NaN
2017-05,3596.0,18.0,18.0,14.0,11.0,12.0,15.0,6.0,9.0,11.0,9.0,12.0,9.0,1.0,7.0,9.0,NaN,NaN,NaN

In [15]:
df.groupby('customer_unique_id').size().value_counts().head(10)

1     92799
2      2728
3       198
4        30
5         8
6         6
7         3
9         1
17        1
Name: count, dtype: int64

In [33]:
cohort_matrix = cohort_matrix.fillna(0)
cohort_matrix.head()

cohort_index,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19
cohort_month,,,,,,,,,,,,,,,,,,,
2017-01,765.0,3.0,2.0,1.0,3.0,1.0,4.0,1.0,1.0,0.0,3.0,1.0,6.0,3.0,1.0,1.0,2.0,3.0,1.0
2017-02,1752.0,4.0,5.0,2.0,7.0,2.0,4.0,3.0,3.0,4.0,2.0,5.0,3.0,3.0,2.0,1.0,1.0,4.0,0.0
2017-03,2636.0,13.0,10.0,10.0,9.0,4.0,4.0,8.0,9.0,2.0,10.0,4.0,6.0,3.0,4.0,6.0,2.0,4.0,0.0
2017-04,2353.0,14.0,5.0,4.0,8.0,6.0,8.0,7.0,7.0,4.0,6.0,2.0,2.0,1.0,2.0,2.0,5.0,0.0,0.0
2017-05,3596.0,18.0,18.0,14.0,11.0,12.0,15.0,6.0,9.0,11.0,9.0,12.0,9.0,1.0,7.0,9.0,0.0,0.0,0.0

In [34]:
retention_matrix = cohort_matrix.divide(
    cohort_matrix[0],
    axis=0
)

retention_matrix = (
    retention_matrix*100
).round(2)

retention_matrix.head()

cohort_index,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19
cohort_month,,,,,,,,,,,,,,,,,,,
2017-01,100.0,0.39,0.26,0.13,0.39,0.13,0.52,0.13,0.13,0.00,0.39,0.13,0.78,0.39,0.13,0.13,0.26,0.39,0.13
2017-02,100.0,0.23,0.29,0.11,0.40,0.11,0.23,0.17,0.17,0.23,0.11,0.29,0.17,0.17,0.11,0.06,0.06,0.23,0.00
2017-03,100.0,0.49,0.38,0.38,0.34,0.15,0.15,0.30,0.34,0.08,0.38,0.15,0.23,0.11,0.15,0.23,0.08,0.15,0.00
2017-04,100.0,0.59,0.21,0.17,0.34,0.25,0.34,0.30,0.30,0.17,0.25,0.08,0.08,0.04,0.08,0.08,0.21,0.00,0.00
2017-05,100.0,0.50,0.50,0.39,0.31,0.33,0.42,0.17,0.25,0.31,0.25,0.33,0.25,0.03,0.19,0.25,0.00,0.00,0.00

In [35]:
retention_matrix = retention_matrix.reset_index()

retention_matrix.head()

cohort_index,cohort_month,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19
0,2017-01,100.0,0.39,0.26,0.13,0.39,0.13,0.52,0.13,0.13,0.00,0.39,0.13,0.78,0.39,0.13,0.13,0.26,0.39,0.13
1,2017-02,100.0,0.23,0.29,0.11,0.40,0.11,0.23,0.17,0.17,0.23,0.11,0.29,0.17,0.17,0.11,0.06,0.06,0.23,0.00
2,2017-03,100.0,0.49,0.38,0.38,0.34,0.15,0.15,0.30,0.34,0.08,0.38,0.15,0.23,0.11,0.15,0.23,0.08,0.15,0.00
3,2017-04,100.0,0.59,0.21,0.17,0.34,0.25,0.34,0.30,0.30,0.17,0.25,0.08,0.08,0.04,0.08,0.08,0.21,0.00,0.00
4,2017-05,100.0,0.50,0.50,0.39,0.31,0.33,0.42,0.17,0.25,0.31,0.25,0.33,0.25,0.03,0.19,0.25,0.00,0.00,0.00

In [36]:
retention_matrix['cohort_month'] = (
    retention_matrix['cohort_month']
    .astype(str)
)
retention_matrix.head()

cohort_index,cohort_month,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19
0,2017-01,100.0,0.39,0.26,0.13,0.39,0.13,0.52,0.13,0.13,0.00,0.39,0.13,0.78,0.39,0.13,0.13,0.26,0.39,0.13
1,2017-02,100.0,0.23,0.29,0.11,0.40,0.11,0.23,0.17,0.17,0.23,0.11,0.29,0.17,0.17,0.11,0.06,0.06,0.23,0.00
2,2017-03,100.0,0.49,0.38,0.38,0.34,0.15,0.15,0.30,0.34,0.08,0.38,0.15,0.23,0.11,0.15,0.23,0.08,0.15,0.00
3,2017-04,100.0,0.59,0.21,0.17,0.34,0.25,0.34,0.30,0.30,0.17,0.25,0.08,0.08,0.04,0.08,0.08,0.21,0.00,0.00
4,2017-05,100.0,0.50,0.50,0.39,0.31,0.33,0.42,0.17,0.25,0.31,0.25,0.33,0.25,0.03,0.19,0.25,0.00,0.00,0.00

In [37]:
retention_matrix.to_sql(
    'cohort_retention_matrix',
    engine,
    if_exists='replace',
    index=False
)

20