In [ ]:
# Customer Lifetime Value Analysis

## Objective
## Analyze customer-level revenue contribution and
## identify distribution of high-value customers.

In [60]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine


engine = create_engine(
    "postgresql://username:password@localhost:5432/ecommerce_db"
)

In [61]:
query = """
SELECT
    customer_unique_id,
    order_purchase_date,
    total_payment
FROM ecommerce_order_view
"""

df = pd.read_sql(query, engine)

In [62]:
df.head()

                 customer_unique_id order_purchase_date  total_payment
0  eb28e67c4c0b83846050ddfb8a35d051          2017-04-26         259.83
1  3818d81c6709e39d06b2738a8d3a2474          2018-01-14         216.87
2  107e6259485efac66428a56f10801f4f          2018-03-24          68.87
3  3fb97204945ca0c01bcf3eee6031c5f1          2018-07-27          57.98
4  7ed0ea20347f67fe61d1c99fdf8556ae          2018-07-24          97.32

In [63]:
clv_df = (
    df.groupby('customer_unique_id').agg(
        {
        'total_payment' : 'sum',
        'order_purchase_date' : 'count'
        }
    )
)
clv_df.head()

                                  total_payment  order_purchase_date
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2         141.90                    1
0000b849f77a49e4a4ce2b2a4ca5be3f          27.19                    1
0000f46a3911fa3c0805444483337064          86.22                    1
0000f6ccb0745a6a4b88665a16c9f078          43.62                    1
0004aac84e0df4da2b147fca70cf8255         196.89                    1

In [64]:
clv_df = clv_df.reset_index()
clv_df.head()

                 customer_unique_id  total_payment  order_purchase_date
0  0000366f3b9a7992bf8c76cfdf3221e2         141.90                    1
1  0000b849f77a49e4a4ce2b2a4ca5be3f          27.19                    1
2  0000f46a3911fa3c0805444483337064          86.22                    1
3  0000f6ccb0745a6a4b88665a16c9f078          43.62                    1
4  0004aac84e0df4da2b147fca70cf8255         196.89                    1

In [65]:
clv_df = clv_df.rename(
    columns = {
         'total_payment' : 'customer_lifetime_value',
        'order_purchase_date' : 'total_order'
    }
)

In [66]:
clv_df[clv_df['total_order']>5].head()

                     customer_unique_id  customer_lifetime_value  total_order
7175   12f5d6e1cbf93dafd9dcc19095df0b3d                   110.72            6
10354  1b6c7548a2a1f9037c1fd3ddfed95f33                   959.01            7
23472  3e43e6105506432c953e165fb2acf44c                  1172.66            9
27043  47c1a3033b8b77b3ab6e109eb4d5fdf3                   944.21            6
37585  63cfc61cee11cbe306bff5857d00bfe4                   826.32            6

In [67]:
clv_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96095 entries, 0 to 96094
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_unique_id       96095 non-null  object
 1   customer_lifetime_value  96095 non-null  float64
 2   total_order              96095 non-null  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 2.2+ MB

In [68]:
clv_df.describe()

       customer_lifetime_value   total_order
count             96095.000000  96095.000000
mean                166.594226      1.034809
std                 231.428912      0.214385
min                   0.000000      1.000000
25%                  63.120000      1.000000
50%                 108.000000      1.000000
75%                 183.530000      1.000000
max               13664.080000     17.000000

In [86]:
clv_df['log_clv'] = np.log1p(
    clv_df['customer_lifetime_value']
)

In [87]:
clv_df.head()

,customer_unique_id,customer_lifetime_value,total_order,log_clv
0,0000366f3b9a7992bf8c76cfdf3221e2,141.90,1,4.962145
1,0000b849f77a49e4a4ce2b2a4ca5be3f,27.19,1,3.338967
2,0000f46a3911fa3c0805444483337064,86.22,1,4.468434
3,0000f6ccb0745a6a4b88665a16c9f078,43.62,1,3.798182
4,0004aac84e0df4da2b147fca70cf8255,196.89,1,5.287711

In [88]:
clv_df = clv_df.rename(
    columns = {
         'log_clv' : 'log_transformed_clv',
    }
)
clv_df.head()

,customer_unique_id,customer_lifetime_value,total_order,log_transformed_clv
0,0000366f3b9a7992bf8c76cfdf3221e2,141.90,1,4.962145
1,0000b849f77a49e4a4ce2b2a4ca5be3f,27.19,1,3.338967
2,0000f46a3911fa3c0805444483337064,86.22,1,4.468434
3,0000f6ccb0745a6a4b88665a16c9f078,43.62,1,3.798182
4,0004aac84e0df4da2b147fca70cf8255,196.89,1,5.287711

In [89]:
clv_df.to_sql(
    name= 'clv_matrix',
    con = engine,
    if_exists='replace',
    index=False
)

95